### ISSUE TITLE
Case à cocher non retenue dans les métadonnées

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#124]
Le type case à cocher est mal géré dans le champs des métadonnées. Cochée ou pas, l'information (attribut et valeur) disparaît des formulaires. 
Or la case à cocher est une des fonctionnalités les plus pratiques d'un formulaire d'échantillon.

**Comment by exmackina** [comment]
analyse en cours

**Comment by exmackina** [comment]
La correction envisagée va avoir un impact local sur les métadonnées sauvegardées en base de données et exportées, on aura {"estblabla":true} au lieu de {"estblabla":"on"} (voir ci-dessous) 
Pour l'instant cela a pour conséquence d'afficher sur la page de consultation du détail d'un échantillon : "estblabla : 1" au lieu de "estblabla : on"; ce dernier point pourra être amélioré.

Techniquement, le "on" résultait de la valeur par défaut d'une checkbox (la valeur d'une checkbox est indépendante de son état coché ou non et ne doit pas être prise pour l'état)
https://html.spec.whatwg.org/multipage/input.html#checkbox-state-(type%3Dcheckbox)
4.10.5.1.15 Checkbox state (type=checkbox)
The value IDL attribute is in mode default/on.
https://html.spec.whatwg.org/multipage/input.html#dom-input-value-default-on
On getting, if the element has a value content attribute, return that attribute's value; otherwise, return the string "on".

**Comment by cplumejeaud** [comment]
Ok, 1 ca irait

**Comment by exmackina** [comment]
NB : à l'heure actuelle, le choix fait n'est pas perdu lors de la sauvegarde des données mais lors de la lecture. Donc la lecture lors d'une modification puis la validation/l'enregistrement (même sans changement) perd le choix fait (l'état coché des checkbox). Avec ce bug il ne faudrait pas modifier les métadonnées (valider la modification) pour ne pas perdre de données initiales qui elles sont correctes.

**Comment by equinton** [comment]
Pas de rustine qui traînerait pendant des années pour rien : il faut corriger intelligemment, avec un script sql adéquat, probablement par l'intermédiaire d'une fonction.

**Comment by equinton** [comment]
Basculement des checkbox en multi-valeurs. Ajout des radio-boutons.
Corrigé dans feature-metadata-mars18
